version: '3.8'
services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - "80:8080"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=secret
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodle_data:/bitnami/moodle
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=secret
volumes:
  moodle_data:
